export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE";

export const EDIT_POST_REQUEST = "EDIT_POST_REQUEST";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const EDIT_POST_FAILURE = "EDIT_POST_FAILURE";

export const GET_POST_REQUEST = "GET_POST_REQUEST";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_FAILURE = "GET_POST_FAILURE";

export const SET_EDITED_POST = "SET_EDITED_POST";

export const SET_EDITED_USER = "SET_EDITED_USER";

export const GET_USERS_COUNT = "GET_USERS_COUNT";

export const GET_TOP_USERS = "GET_TOP_USERS";

export const GET_POSTS_COUNT = "GET_POSTS_COUNT";

export const GET_TOP_POSTS = "GET_TOP_POSTS";

export const GET_ALL_USERS = "GET_ALL_USERS";

export const DELETE_USER = "DELETE_USER";

export const EDIT_USER = "EDIT_USER";

export const LIKE = "LIKE";

export const UNLIKE = "UNLIKE";
