export const LOGIN__REQUEST = "LOGIN__REQUEST";
export const LOGIN__SUCEESS = "LOGIN__SUCCESS";
export const LOGIN__FAILURE = "LOGIN__FAILURE";

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";